### ISSUE TITLE
Update prv-moves runtime dependency.

### ISSUE THREAD

**Issue by zw963** [garmoshka-mo/pry-moves#4]
Current this gem add pry as dependency, and fetch older pry version.

```rb
gem.add_runtime_dependency 'pry', '>= 0.10.4', '< 0.12.0'
```

But current pry stable version is 0.12.2.

Thanks

**Comment by garmoshka-mo** [comment]
Probably we can remove upper edge for `pry`
PR is welcomed if you'll have a chance to commit

**Comment by zw963** [comment]
#7

**Comment by zw963** [comment]
one question, i see pry have watch command builtin, why we add a new watch command?

Thank you.

**Comment by TylerRick** [comment]
Yes, let's remove the upper version limit! #8 does that.

It always bugs me when gems pessimistically lock to a minor version number (with minimum patch level, like `~> 0.10.4`, which means it won't work with `0.11`) or set a pessimistic upper version limit on a dependency. That's just _guaranteeing_ that users will run into dependency issues as soon as they try to upgrade one of its dependencies and will _have_ to open a new PR for every single minor version bump of a dependency.

I think it's better to be optimistic and assume that your gem _will_ work with minor version bumps of each  dependency (unless said dependency has a history or policy of introducing breaking changes in minor version bumps). Then no intervention or extra work is required for the users or maintainers of the gem. If someone _does_ ran into a problem using it with a later version of a dependency, _then_ they can open an issue/PR that adds a maximum version/range as needed (and release a patch release with that updated dependency locking).

Since everyone _should_ be using semver :), then it should be safe to only lock to a _major_ version number (with minimum minor version, like `~>0.10`, allowing it to work with anything `< 1.0`).

**Comment by garmoshka-mo** [comment]
thank you for explanation of removing of upper version, @TylerRick

**Comment by garmoshka-mo** [comment]
@zw963 with regards to `watch` function - i tried pry's version - i'm not sure, what it's intended for (or how to properly integrate it with pry-moves)
Intention of re-implemented `watch` is to show value of variable on each movement (e.g. you type `n` and see output of value for watched variables)
